name: deploy-to-digitalocean
on:
  push:
    branches:
      - main

jobs:
  build-astro-project-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - run: yarn
    - run: yarn run build

                  
    - name: Install SSH Key   
      uses: shimataro/ssh-key-action@v2.6.1
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - run: cat ~/.ssh/known_hosts
    
    - run: rsync -r ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html
  
  

  
  
